# Generated by Django 6.1.2 on 2026-10-08 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(default='Candidate', max_length=100)),
                ('domain', models.CharField(default='web_dev', max_length=50)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('mode', models.CharField(choices=[('drill', 'Quick Drill'), ('mock', 'Full Mock Interview')], default='drill', max_length=20)),
                ('target_questions', models.IntegerField(default=5)),
                ('overall_score', models.FloatField(default=0.0)),
                ('technical_score', models.FloatField(default=0.0)),
                ('concept_score', models.FloatField(default=0.0)),
                ('depth_score', models.FloatField(default=0.0)),
                ('communication_score', models.FloatField(default=0.0)),
                ('verdict', models.CharField(blank=True, default='Pending', max_length=50)),
                ('summary_feedback', models.TextField(blank=True, default='')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('web_dev', 'Web Development'), ('ds', 'Data Science & ML'), ('dsa', 'Data Structures & Algorithms'), ('hr', 'HR & Behavioral'), ('project_defense', 'Live Demo: Project Defense')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('category', models.CharField(default='Core Concepts', max_length=100)),
                ('key_concepts', models.TextField(help_text='Comma or newline-separated expected concepts/terms')),
                ('model_answer', models.TextField(help_text='Gold-standard interviewer model answer')),
                ('hints', models.TextField(blank=True, default='')),
                ('rubric_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['domain', 'difficulty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
                ('answer_method', models.CharField(default='typed', max_length=20)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('grade', models.CharField(default='C', max_length=20)),
                ('semantic_similarity', models.FloatField(default=0.0)),
                ('concept_coverage', models.FloatField(default=0.0)),
                ('depth_score', models.FloatField(default=0.0)),
                ('structure_score', models.FloatField(default=0.0)),
                ('feedback_data', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='interviews.interviewsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='interviews.question')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
    ]
