# Generated by Django 6.1.2 on 2026-10-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersubmission',
            name='turn_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='behavioral_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='presence_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
